### PR TITLE
JENKINS-64452 Compatibility with Jenkins core >=2.271

### PR DESCRIPTION
**Pull request by timja**
See https://issues.jenkins.io/browse/JENKINS-64452

Requires https://github.com/jenkinsci/azure-commons-plugin/pull/51

Also install https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-commons/1.0.6-rc220.c094849fd287/azure-commons-1.0.6-rc220.c094849fd287.hpi when testing

cc @xuzhang3 

tested manually and I can login

Fixes https://github.com/jenkinsci/azure-ad-plugin/issues/91

### CODE REVIEW

**Comment by timja** [comment]
Tested manually and confirmed by someone who uses the plugin: https://github.com/jenkinsci/azure-ad-plugin/issues/91#issuecomment-749118814

**Comment by xuzhang3** [comment]
@timja  Does test common-plugin: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-commons/1.0.6-rc220.c094849fd287/azure-commons-1.0.6-rc220.c094849fd287.hpi   build from  branch  https://github.com/timja/azure-commons-plugin/tree/tables-to-divs ? I try install the test plugin, but other plugins depend on azure-commons-plugin can not be loaded, Jenkins can not start.

**Comment by timja** [comment]
> @timja Does test common-plugin: [repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-commons/1.0.6-rc220.c094849fd287/azure-commons-1.0.6-rc220.c094849fd287.hpi](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-commons/1.0.6-rc220.c094849fd287/azure-commons-1.0.6-rc220.c094849fd287.hpi) build from branch [https://github.com/timja/azure-commons-plugin/tree/tables-to-divs](https://github.com/timja/azure-commons-plugin/tree/tables-to-divs?rgh-link-date=2020-12-22T09%3A55%3A13Z) ? I try install the test plugin, but other plugins depend on azure-commons-plugin can not be loaded, Jenkins can not start.

What's the error you get?

**Comment by xuzhang3** [comment]
@timja   LGTM

**Pull request merged**
