### PR TITLE
Disable Single Logout by default

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/azure-ad-plugin/issues/124

fyi @joaonatividade-vakt

### CODE REVIEW

**Comment by joaonatividade-vakt** [comment]
Hi @timja thank you very much for your work and feedback given. Is there any estimation as to when this enhancement will be released?

João Natividade

**Comment by joaonatividade-vakt** [comment]
@timja, I'm already testing the new plugin version :)  However, when hitting the "log out" button nothing really happens (**I remain signed in**). There's nothing special going on in the logs (/var/log/jenkins/jenkins.log) as well, I just get this:
`2021-05-10 09:25:53.847+0000 [id=16]	INFO	c.m.j.azuread.AzureSecurityRealm#doFinishLogin: Requesting oauth code time = 536 ms` 
Did you experience something similar when you were testing these changes?

Thank you in advance!
João Natividade

**Comment by timja** [comment]
> @timja, I'm already testing the new plugin version :) However, when hitting the "log out" button nothing really happens (**I remain signed in**). There's nothing special going on in the logs (/var/log/jenkins/jenkins.log) as well, I just get this:
> `2021-05-10 09:25:53.847+0000 [id=16] INFO c.m.j.azuread.AzureSecurityRealm#doFinishLogin: Requesting oauth code time = 536 ms`
> Did you experience something similar when you were testing these changes?
> 
> Thank you in advance!
> João Natividade

Well you're getting logged out and then logged straight in, check your network logs in the browser.

If you have multiple accounts logged in you'll see you're getting prompted to log in again.

Or if you grant Overall/Read to anonymous user you'll land on the home page with a button to click log in

**Comment by joaonatividade-vakt** [comment]
@timja my ISO is not happy with this approach (:D) as it represents a security risk as we give anyone the ability to see the list of all the provisioned users. Would it be possible for you to change it so that we don't require any permissions for the log-out functionality to work?

**Comment by timja** [comment]
Can you raise a new issue? I think the saml plugin has a 'logged out' page that you could be sent to instead of the home page.

**Pull request merged**
