### PR TITLE
[JENKINS-64858] - Enabled support for Job DSL plugin

### PR DESCRIPTION
**Pull request by hrmohr**
This PR fixes [JENKINS-64858](https://issues.jenkins.io/browse/JENKINS-64858) enabling the use of the following Job DSL syntax:

```
folder('project-a') {
  displayName('Project A')
  description('Folder for project A')
  properties {
    azureAdAuthorizationMatrix {
      inheritanceStrategy {
        inheriting()
      }
      permissions(['hudson.model.Item.Create:authenticated'])
    }
  }
}


freeStyleJob('project-a/example') {
  properties {
    azureAdAuthorizationMatrix {
      inheritanceStrategy {
        nonInheriting()
      }
      permissions(['hudson.model.Item.Workspace:authenticated'])
    }
  }
}
```

### CODE REVIEW

**Comment by baowei** [comment]
i need it,greate

**Comment by baowei** [comment]
when can this PR be merged? I need it

**Comment by hrmohr** [comment]
@xuzhang3 perhaps you could have a look? or @jenkinsci/azure-devops-team ?

**Review by timja — APPROVED** [review]

**Comment by angel-moveapps** [comment]
Hi @hrmohr, can you help me with this error?

```
ERROR: (my_job.groovy, line 14) No signature of method: javaposse.jobdsl.plugin.structs.DescribableContext.permissions() is applicable for argument types: (java.lang.String, java.util.ArrayList) values: [GRP_JenkinsAdmin, [hudson.model.Item.Read, hudson.model.Item.Discover]]
```

I'm using this code:

```
properties {
        azureAdAuthorizationMatrix {
            permissions('GRP_JenkinsAdmin', [
                'hudson.model.Item.Discover',
                'hudson.model.Item.Read'
            ])
        }
    }
```

**Pull request merged**
