### PR TITLE
Add URL rewrite for node creation

### LINKED ISSUE #199: 405 method not allowed on create agent screen
### Jenkins and plugins versions report

-

### What Operating System are you using (both controller, and any agents involved in the problem)?

-

### Reproduction steps

 http://localhost:8080/computer/createItem

VM522:1          GET http://localhost:8082/computer/createItem/GraphProxy/v1.0/me 405 (Method Not Allowed)

### Expected Results

-

### Actual Results

-

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by meiswjn**
Fixes #199 by adding a new URL rewrite to prevent Jenkins Core from handling the request in a wrong way. 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Co-Authored by @StefanSpieker

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Looks reasonable you've tested this as working?

**Comment by meiswjn** [comment]
Initial fix is working for #199 but does not fully resolve #278. One sec.

**Comment by meiswjn** [comment]
Both issues are resolved on the test instance. Let me know what you think! :)

**Comment by timja** [comment]
I'll need to have a closer look, I would have expected there to be a cleaner way to do it.

**Comment by timja** [comment]
Would #278 be fixed instead by https://github.com/jenkinsci/azure-ad-plugin/pull/276 ?

**Comment by meiswjn** [comment]
Should we split up the PR into two PRs?

**Comment by timja** [comment]
> Not sure. Is it testable already? Asking because it is a draft

Yes its testable, the main remaining work is testing.

---

> Should we split up the PR into two PRs?

Sure, the createItem fix is fine

**Comment by timja** [comment]
oh hai Stefan

**Pull request merged**
