### PR TITLE
fix jcasc test harness

### PR DESCRIPTION
**Pull request by casz**
JCasc had to create a new dependency that wasn't a tests classifier because maven doesn't allow you to bring dependencies through classifiers.

Upgrading here so that PCT works again,

Tracking:
jenkinsci/bom#164

Note: We'll need a release for PCT please

### CODE REVIEW

**Comment by casz** [comment]
damnmit ci.jenkins.io and your ClosedChannelException 😭

**Comment by casz** [comment]
Like many of my other PRs 😓
I wonder why azure pipeline passes?

**Comment by gavinfish** [comment]
> Like many of my other PRs 😓
> I wonder why azure pipeline passes?

The azure pipeline now only makes sure no secrets are exposed by accident. It will not build the project.

**Comment by casz** [comment]
I created a separate PR for the last two commits.
You can choose to merge #73 first and than squash and merge this one.

**Pull request merged**
