### PR TITLE
Async granting group permission

### LINKED ISSUE #47: Slowness on inital authorization
Hi,

When logging into Jenkins for the first time in a while, it will take upwards of 30 seconds to authorize.  I'm wondering if the plugin itself is slow or if it's our Azure AD setup.  Does anyone else see this?

Thanks,
Eric

### PR DESCRIPTION
**Pull request by gavinfish**
Try to fix #47.

I use some profiler to analysis my local development environment and find that the method “validateAndParseIdToken” occupies a large proportion even the finishLogin call does not last long. 
 
 
temp

The `validateAndParseIdToken` method both validates the token to avoid CSRF attack and grant current Jenkins user authorities from Azure AD users and groups. The slowness of the method may be caused by the combination of the following pull requests:
-	Implement support for named groups and users #39 fetches groups information from the AD server will make a request for each of the groups
-	Upgrade Microsoft identity platform from v1.0 to v2.0 #41 checks AAD setting to find out whether it is able to fetch group information
 
So when your AAD user belongs to lots of groups, the checking and communication with AAD service may take a long time to finish.

### CODE REVIEW

**Comment by gavinfish** [comment]
One possible solution here is to try to fetch the group information in another thread and update the authentication later. So that the rendering page will not be blocked for a really long time. But this may cause some users cannot have right permission immediately if the matrix is only set for the groups.

**Comment by Yatheesh-Rai** [comment]
@gavinfish 
I did round of testing after installing the snapshot plugin in  dev JOC and master. Now the request redirected to Microsoft Oauth/authorize responding fast and home page rendering takes less time. I request you to release the plugin with this feature and make it available in Jenkins update center.

**Comment by Yatheesh-Rai** [comment]
Thanks a lot for fixing this problem. This is of great help for the Jenkins users.

**Comment by Yatheesh-Rai** [comment]
@gavinfish 
If we add this feature, is there any impact for some Jenkins-users ? In your previous comment, you have mentioned "may cause some users".

**Comment by gavinfish** [comment]
@Yatheesh-Rai If some Jenkins users use `groupName (principalName)` to configure their matrix, this change will block them login successfully at once. This change grant privileges asynchronously for group, so it may take some time before group users could login. They need refresh the page after some time to successfully login the system.

**Comment by Yatheesh-Rai** [comment]
@gavinfish 
Thanks for the response!

Did you find a fix for the above problem ? (If some Jenkins users use groupName (principalName) to configure their matrix, this change will block them login successfully at once)

Can you please let us know when can we expect the plugin to be released in update centre.
Because many users have started complaining about oauth response slowness

Thanks again for the support !

**Comment by Yatheesh-Rai** [comment]
@gavinfish 
It would be great if you can release the plugin this week, so that we can push the upgraded plugin to production this week end.

**Comment by snallami** [comment]
> @Yatheesh-Rai If some Jenkins users use `groupName (principalName)` to configure their matrix, this change will block them login successfully at once. This change grant privileges asynchronously for group, so it may take some time before group users could login. They need refresh the page after some time to successfully login the system.

@gavinfish
What does above comment mean? Does it mean that if `groupName (principalName)` is configured at jenkins global configuration then user won't me able to login upon first try? Or are we talking about job level permissions? (Currently we are seeing performance issues during login and looking forward for this fix)

**Comment by gavinfish** [comment]
@snallami all the group related permissions won't take effect immediately since the performance issues are caused by that. It may take some time for the group authenticated users to login(refresh the page).

**Comment by gavinfish** [comment]
@Yatheesh-Rai released as 1.1.0.

**Comment by snallami** [comment]
Great. Thank You, @gavinfish 

(Side note: not related to this PR. Does Azure AD plugin cache user group data ? If yes what is the refresh interval.)

**Comment by Yatheesh-Rai** [comment]
> @Yatheesh-Rai released as 1.1.0.

Thanks a lot @gavinfish

**Comment by gavinfish** [comment]
@snallami no, it is only refreshed when Jenkins needs to authenticate again.

**Comment by Yatheesh-Rai** [comment]
Hi @gavinfish 

With the plugin version 1.1.0 we have seen very strange behaviour where in Jenkins EC2 plugin configuration completely wiped off from the global config.xml , this caused a major impact, couldn't provision the elastic agents from AWS.

Also we have noticed some links or buttons does n't show up unless we load twice or thrice. This is also a side effect of azure ad plugin upgrade to 1.1.0

Third issue that we have observed after installing the plugin , immediately after the restart of Jenkins, when rendering the home page  it shows "user missing the overall permission". We had to reload the page again to vanish the red message.


Please take a look.
Thanks in advance.

Thanks
Yatheesh

**Pull request merged**
